### ISSUE TITLE
Separate and store initialised population

### ISSUE THREAD

**Issue by laraherriott** [SABS-R3-Epidemiology/epiabm#176]
For continued speed updates, if we want to run multiple simulations with the same population e.g. with different interventions, is there a way the initialised population (i.e. ages, household assignment etc.) can be stored in that state and reused each time.

**Comment by KCGallagher** [comment]
@laraherriott This was the original aim of the `FilePopulationConfig.print_population()` functionality. However this does not store data on an individual level, as you suggest. This is because the memory associated with storing this in a readable way would be significant, and it is typically not time consuming to recreate this from the current population files (indeed the time consuming step was location allocation which this method avoids).

If you want to store the complete population, I think the best method would be using [pickle](https://docs.python.org/3/library/pickle.html) to store a compressed version of the object (non-human readable, so must be de-serialised by python).
